// Package api serves the REST + SSE endpoints and the embedded web UI.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io/fs"
	"log/slog"
	"net"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/openvtl/openvtld/internal/config"
	"github.com/openvtl/openvtld/internal/events"
	"github.com/openvtl/openvtld/internal/export"
	"github.com/openvtl/openvtld/internal/inventory"
	"github.com/openvtl/openvtld/internal/orchestrate"
	"github.com/openvtl/openvtld/internal/storage"
	"github.com/openvtl/openvtld/internal/store"
)

type Server struct {
	cfg       *config.Config
	inv       *inventory.Engine
	bus       *events.Bus
	db        *store.Store
	runner    *export.Runner
	fc        *orchestrate.FC
	stor      *storage.Manager
	log       *slog.Logger
	ui        fs.FS
	mux       *http.ServeMux
	version   string
	buildDate string // ldflags buildDate — the update-ordering key
	started   time.Time

	// setupDone latches true once the first admin exists; until then the
	// middleware answers 409 setup_required to everything but setup.
	setupDone atomic.Bool
	// draining: a graceful restart is waiting for jobs to finish; new
	// job-creating calls are refused until it fires or times out.
	draining atomic.Bool
	// mintMu serializes cart creation so concurrent requests can't
	// allocate the same autogenerated label from equal snapshots.
	mintMu sync.Mutex
}

func New(cfg *config.Config, inv *inventory.Engine, bus *events.Bus, db *store.Store, runner *export.Runner, fc *orchestrate.FC, stor *storage.Manager, ui fs.FS, log *slog.Logger, version, buildDate string) *Server {
	s := &Server{cfg: cfg, inv: inv, bus: bus, db: db, runner: runner, fc: fc, stor: stor, ui: ui, log: log, mux: http.NewServeMux(), version: version, buildDate: buildDate, started: time.Now()}
	s.mux.HandleFunc("GET /healthz", s.healthz)
	s.mux.HandleFunc("GET /metrics", s.metrics)
	s.mux.HandleFunc("GET /api/status", s.status)
	s.mux.HandleFunc("GET /api/library", s.library)
	s.mux.HandleFunc("GET /api/cartridges", s.cartridges)
	s.mux.HandleFunc("GET /api/cartridges/{label}", s.cartridge)
	s.mux.HandleFunc("GET /api/events/recent", s.recentEvents)
	s.mux.HandleFunc("GET /api/events/search", s.searchEvents)
	s.mux.HandleFunc("GET /api/events", s.sse)

	// v0.4 — export/import pipeline (first mutating routes; audited)
	s.mux.HandleFunc("GET /api/remotes", s.listRemotes)
	s.mux.HandleFunc("POST /api/remotes", s.createRemote)
	s.mux.HandleFunc("PUT /api/remotes/{id}", s.updateRemote)
	s.mux.HandleFunc("DELETE /api/remotes/{id}", s.deleteRemote)
	s.mux.HandleFunc("POST /api/remotes/{id}/test", s.testRemote)
	s.mux.HandleFunc("GET /api/remotes/{id}/objects", s.listBucketObjects)
	s.mux.HandleFunc("DELETE /api/remotes/{id}/objects", s.deleteBucketPrefix)
	s.mux.HandleFunc("GET /api/jobs", s.listJobs)
	s.mux.HandleFunc("GET /api/jobs/search", s.searchJobs)
	s.mux.HandleFunc("GET /api/jobs/{id}", s.getJob)
	s.mux.HandleFunc("POST /api/jobs/{id}/retry", s.retryJob)
	s.mux.HandleFunc("POST /api/jobs/{id}/cancel", s.cancelJob)
	s.mux.HandleFunc("POST /api/cartridges/{label}/export", s.exportCart)
	s.mux.HandleFunc("POST /api/cartridges/{label}/evict", s.evictCart)
	s.mux.HandleFunc("POST /api/cartridges/{label}/import", s.importCart)
	s.mux.HandleFunc("POST /api/libraries/{lib}/drives/{index}/load", s.loadDrive)
	s.mux.HandleFunc("POST /api/libraries/{lib}/drives/{index}/unload", s.unloadDrive)
	s.mux.HandleFunc("GET /api/catalog", s.listCatalog)
	s.mux.HandleFunc("POST /api/catalog/rebuild", s.rebuildCatalog)
	s.mux.HandleFunc("GET /api/settings", s.getSettings)
	s.mux.HandleFunc("PUT /api/settings", s.putSettings)
	s.mux.HandleFunc("GET /api/audit", s.recentAudit)

	// v0.5 — session auth + user management
	s.mux.HandleFunc("POST /api/auth/setup", s.authSetup)
	s.mux.HandleFunc("POST /api/auth/login", s.authLogin)
	s.mux.HandleFunc("POST /api/auth/logout", s.authLogout)
	s.mux.HandleFunc("GET /api/auth/me", s.authMe)
	s.mux.HandleFunc("GET /api/users", s.listUsers)
	s.mux.HandleFunc("POST /api/users", s.createUser)
	s.mux.HandleFunc("PUT /api/users/{id}", s.updateUser)
	s.mux.HandleFunc("PUT /api/users/{id}/password", s.setUserPassword)
	s.mux.HandleFunc("DELETE /api/users/{id}", s.deleteUser)

	// v0.5 — Targets & ACLs (list-shaped: multi-target is a forward
	// requirement even though exactly one qla2xxx target exists today)
	s.mux.HandleFunc("GET /api/targets", s.getTargets)
	s.mux.HandleFunc("POST /api/targets/acls", s.addTargetACL)
	s.mux.HandleFunc("PUT /api/targets/acls/{wwpn}", s.updateTargetACL)
	s.mux.HandleFunc("DELETE /api/targets/acls/{wwpn}", s.removeTargetACL)
	// v0.7 — per-port serving toggle (additive on the live config
	// except explicit disables)
	s.mux.HandleFunc("PUT /api/targets/ports", s.putPortServing)
	s.mux.HandleFunc("GET /api/pool/history", s.poolHistory)
	s.mux.HandleFunc("POST /api/cartridges", s.mintCart)
	s.mux.HandleFunc("DELETE /api/cartridges/{label}", s.deleteCart)

	// v0.7 UI batch 3 — system control + API access keys
	s.mux.HandleFunc("GET /api/license", s.licenseInfo)
	s.mux.HandleFunc("POST /api/license/ack", s.licenseAck)
	s.mux.HandleFunc("GET /api/system", s.systemInfo)
	s.mux.HandleFunc("POST /api/system/restart", s.systemRestart)
	s.mux.HandleFunc("POST /api/system/dataplane-restart", s.dataplaneRestart)
	s.mux.HandleFunc("POST /api/system/reboot", s.rebootHost)
	s.mux.HandleFunc("GET /api/system/support-bundle", s.supportBundle)
	// v0.9 — in-UI Updates: upload + detached apply
	s.mux.HandleFunc("GET /api/system/update-status", s.updateStatus)
	s.mux.HandleFunc("POST /api/system/update", s.uploadUpdate)
	s.mux.HandleFunc("POST /api/system/rollback", s.rollbackUpdate)
	s.mux.HandleFunc("GET /api/apikeys", s.listAPIKeys)
	s.mux.HandleFunc("POST /api/apikeys", s.createAPIKey)
	s.mux.HandleFunc("DELETE /api/apikeys/{id}", s.deleteAPIKey)

	// v0.6 — multi-library & storage pools
	s.mux.HandleFunc("GET /api/models", s.listModels)
	s.mux.HandleFunc("GET /api/devices", s.listDevices)
	s.mux.HandleFunc("GET /api/pools", s.listPools)
	s.mux.HandleFunc("POST /api/pools", s.createPool)
	s.mux.HandleFunc("DELETE /api/pools/{id}", s.removePool)
	s.mux.HandleFunc("POST /api/storage/setup", s.setupStorage)
	s.mux.HandleFunc("POST /api/storage/teardown", s.teardownStorage)
	s.mux.HandleFunc("POST /api/storage/grow", s.growStorage)
	s.mux.HandleFunc("POST /api/storage/rescan", s.rescanDevices)
	s.mux.HandleFunc("GET /api/libraries", s.listLibraries)
	s.mux.HandleFunc("GET /api/libraries/{lib}/next-label", s.nextLabel)
	s.mux.HandleFunc("POST /api/libraries", s.createLibrary)
	s.mux.HandleFunc("DELETE /api/libraries/{lib}", s.deleteLibrary)
	s.mux.HandleFunc("POST /api/libraries/apply", s.applyLibraries)
	s.mux.HandleFunc("POST /api/libraries/recover", s.recoverLibrary)

	s.mux.HandleFunc("GET /", s.static)
	return s
}

func (s *Server) Handler() http.Handler { return s.requireAuth(s.mux) }

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	_ = json.NewEncoder(w).Encode(v)
}

func (s *Server) healthz(w http.ResponseWriter, _ *http.Request) {
	// version is unauthenticated (already in -version and the support bundle):
	// the update health-probe reads it to confirm the NEW binary is the one now
	// serving before clearing the pending-update marker.
	writeJSON(w, 200, map[string]any{"ok": true, "ts": time.Now().UTC(), "version": s.version})
}

// metrics emits Prometheus text format by hand — a handful of gauges
// doesn't justify the client_golang dependency tree. Job counters are
// derived from the DB at scrape time (restart-proof); pool and drive
// series carry pool/library labels from the start so a second pool
// or library won't break dashboards.
func (s *Server) metrics(w http.ResponseWriter, r *http.Request) {
	snap := s.inv.Snapshot()
	w.Header().Set("Content-Type", "text/plain; version=0.0.4")
	p := func(format string, a ...any) { fmt.Fprintf(w, format+"\n", a...) }

	// ZFS storage plane (v0.7): per-pool filesystem + logical (pre-dedup/
	// compress) sizes, per-dataset compression, and the pool-wide dedupe
	// ratio (the shared dedup vdev serves every dataset).
	p("# TYPE openvtl_pool_fs_used_bytes gauge")
	p("# TYPE openvtl_pool_fs_total_bytes gauge")
	p("# TYPE openvtl_pool_logical_bytes gauge")
	p("# TYPE openvtl_pool_dedup_ratio gauge")
	p("# TYPE openvtl_pool_compress_ratio gauge")
	// phys_est ≈ dataset used ÷ global dedupratio — the honest per-pool
	// disk share (fs_used is post-compression only and exceeds the pool
	// size under heavy dedup); the zpool gauges are the real fill level.
	p("# TYPE openvtl_pool_phys_est_bytes gauge")
	p("# TYPE openvtl_zpool_alloc_bytes gauge")
	p("# TYPE openvtl_zpool_size_bytes gauge")
	for i, pool := range snap.Pools {
		p(`openvtl_pool_fs_used_bytes{pool=%q} %d`, pool.Name, pool.FSUsedBytes)
		p(`openvtl_pool_fs_total_bytes{pool=%q} %d`, pool.Name, pool.FSTotalBytes)
		p(`openvtl_pool_logical_bytes{pool=%q} %d`, pool.Name, pool.LogicalBytes)
		p(`openvtl_pool_dedup_ratio{pool=%q} %.3f`, pool.Name, pool.DedupRatio)
		p(`openvtl_pool_compress_ratio{pool=%q} %.3f`, pool.Name, pool.CompressRatio)
		p(`openvtl_pool_phys_est_bytes{pool=%q} %d`, pool.Name, pool.PhysEstBytes)
		if i == 0 { // zpool figures are system-wide (identical on every pool)
			p(`openvtl_zpool_alloc_bytes %d`, pool.ZpoolAllocBytes)
			p(`openvtl_zpool_size_bytes %d`, pool.ZpoolSizeBytes)
		}
	}

	p("# TYPE openvtl_fc_target_verified gauge")
	v := 0
	if snap.FC.Verified {
		v = 1
	}
	p("openvtl_fc_target_verified %d", v)

	serialOf := map[int]string{}
	p("# TYPE openvtl_drive_blocks_written counter")
	p("# TYPE openvtl_drive_blocks_read counter")
	for _, l := range snap.Libraries {
		serialOf[l.Library.ID] = l.Library.Serial
		for _, d := range l.Drives {
			p(`openvtl_drive_blocks_written{library=%q,drive="%d"} %d`, l.Library.Serial, d.Index, d.BlocksWritten)
			p(`openvtl_drive_blocks_read{library=%q,drive="%d"} %d`, l.Library.Serial, d.Index, d.BlocksRead)
		}
	}

	// Job outcomes/bytes/durations — the v0.5 "Grafana-able" additions.
	if stats, err := s.db.JobStats(r.Context()); err == nil {
		p("# TYPE openvtl_jobs_total counter")
		p("# TYPE openvtl_job_bytes_total counter")
		p("# TYPE openvtl_job_duration_seconds_total counter")
		for _, j := range stats {
			p(`openvtl_jobs_total{kind=%q,outcome=%q} %d`, j.Kind, j.Outcome, j.Count)
			p(`openvtl_job_bytes_total{kind=%q,outcome=%q} %d`, j.Kind, j.Outcome, j.Bytes)
			p(`openvtl_job_duration_seconds_total{kind=%q,outcome=%q} %d`, j.Kind, j.Outcome, j.DurationSec)
		}
	}
	if counts, err := s.db.CartStateCounts(r.Context()); err == nil {
		p("# TYPE openvtl_carts gauge")
		for _, c := range counts {
			p(`openvtl_carts{library=%q,local_state=%q} %d`, serialOf[c.LibraryID], c.LocalState, c.Count)
		}
	}
	// Live initiator logins (configfs/sysfs reads — cheap on the
	// scrape path). Per-fabric since v0.7's multi-port registry.
	byFabric := map[string]int{}
	for _, iv := range s.fc.Initiators(r.Context()) {
		if iv.LoggedIn {
			byFabric[iv.Fabric]++
		}
	}
	p("# TYPE openvtl_target_sessions_active gauge")
	for fabric, n := range byFabric {
		p(`openvtl_target_sessions_active{fabric=%q} %d`, fabric, n)
	}
}

// libraryOut / librarySnapOut decorate the live snapshot with the
// persisted display name (v0.7: names shown everywhere, serial stays
// the host-facing identity as subtext).
type libraryOut struct {
	inventory.Library
	Name string `json:"name"`
}

type librarySnapOut struct {
	inventory.LibrarySnapshot
	Library libraryOut `json:"library"`
}

// fabricsOut feeds the header's aggregate fabric chip: FC state + live
// session count in one glance (additive; snapshot.fc unchanged).
type fabricsOut struct {
	FC struct {
		Present  bool   `json:"present"`
		Verified bool   `json:"verified"`
		Detail   string `json:"detail"`
		Sessions int    `json:"sessions"`
	} `json:"fc"`
}

func (s *Server) status(w http.ResponseWriter, r *http.Request) {
	// The outer fields shadow Snapshot's (shallower depth wins in
	// encoding/json): Carts carries the same local_state /
	// last_export_gen join as /api/cartridges, Libraries the display
	// names. Initiators is a configfs/sysfs read — cheap on this path
	// (same reasoning as /metrics).
	snap := s.inv.Snapshot()
	names := map[int]string{}
	if rows, err := s.db.ListLibraries(r.Context()); err == nil {
		for _, l := range rows {
			names[l.ID] = l.Name
		}
	}
	libs := make([]librarySnapOut, 0, len(snap.Libraries))
	for _, l := range snap.Libraries {
		name := names[l.Library.ID]
		if name == "" {
			name = l.Library.Serial
		}
		libs = append(libs, librarySnapOut{LibrarySnapshot: l, Library: libraryOut{Library: l.Library, Name: name}})
	}

	// FC presence comes from the live fc_host port count — the
	// snapshot's FCState is the aggregate target state.
	var fab fabricsOut
	fab.FC.Present, fab.FC.Verified, fab.FC.Detail = s.fc.HBAPresent(), snap.FC.Verified, snap.FC.Detail
	for _, iv := range s.fc.Initiators(r.Context()) {
		if iv.LoggedIn {
			fab.FC.Sessions++
		}
	}

	writeJSON(w, 200, struct {
		inventory.Snapshot
		Libraries []librarySnapOut `json:"libraries"`
		Carts     []cartOut        `json:"cartridges"`
		Fabrics   fabricsOut       `json:"fabrics"`
	}{snap, libs, s.cartsWithMeta(r), fab})
}

func (s *Server) library(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, 200, map[string]any{
		"libraries": s.inv.Snapshot().Libraries,
	})
}

// cartOut joins live inventory with persisted per-cart state (eviction
// stubs, last export generation).
type cartOut struct {
	inventory.Cart
	LocalState    string `json:"local_state"`
	LastExportGen string `json:"last_export_gen,omitempty"`
}

func (s *Server) cartsWithMeta(r *http.Request) []cartOut {
	metas, err := s.db.CartMetas(r.Context())
	if err != nil {
		s.log.Warn("cart metas", "err", err)
	}
	carts := s.inv.Snapshot().AllCarts()
	out := make([]cartOut, 0, len(carts))
	for _, c := range carts {
		co := cartOut{Cart: c, LocalState: "resident"}
		if m, ok := metas[c.Label]; ok {
			co.LocalState, co.LastExportGen = m.LocalState, m.LastExportGen
		}
		out = append(out, co)
	}
	return out
}

func (s *Server) cartridges(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, 200, s.cartsWithMeta(r))
}

func (s *Server) cartridge(w http.ResponseWriter, r *http.Request) {
	label := r.PathValue("label")
	for _, c := range s.cartsWithMeta(r) {
		if c.Label == label {
			writeJSON(w, 200, c)
			return
		}
	}
	writeJSON(w, 404, map[string]string{"error": "unknown cartridge"})
}

// poolHistory serves persisted dedupe_stats samples so the dashboard
// capacity trend survives restarts (v0.4's was session-only). ?pool=
// selects a pool; default is the first in the snapshot (legacy series
// name pre-rebuild).
func (s *Server) poolHistory(w http.ResponseWriter, r *http.Request) {
	hours := 24
	if h, err := strconv.Atoi(r.URL.Query().Get("hours")); err == nil && h > 0 && h <= 24*90 {
		hours = h
	}
	pool := r.URL.Query().Get("pool")
	if pool == "" {
		if pools := s.inv.Snapshot().Pools; len(pools) > 0 {
			pool = pools[0].Name
		} else {
			pool = s.cfg.VDOLV
		}
	}
	samples, err := s.db.PoolHistory(r.Context(), pool, time.Now().Add(-time.Duration(hours)*time.Hour))
	if err != nil {
		serverError(w, err)
		return
	}
	if samples == nil {
		samples = []store.PoolSample{}
	}
	writeJSON(w, 200, samples)
}

func (s *Server) recentEvents(w http.ResponseWriter, r *http.Request) {
	evs, err := s.db.RecentEvents(r.Context(), 200)
	if err != nil {
		writeJSON(w, 500, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, 200, evs)
}

// searchEvents runs a deep query over the whole persisted event_log — a
// free-text match (q) and/or an exact kind, newest first. The journal
// viewer uses it to reach past the 200-row recent window.
func (s *Server) searchEvents(w http.ResponseWriter, r *http.Request) {
	q := strings.TrimSpace(r.URL.Query().Get("q"))
	kind := r.URL.Query().Get("kind")
	if kind == "all" {
		kind = ""
	}
	limit := 500
	if v := r.URL.Query().Get("limit"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			limit = n
		}
	}
	evs, err := s.db.SearchEvents(r.Context(), q, kind, limit)
	if err != nil {
		writeJSON(w, 500, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, 200, evs)
}

// sse streams the event bus. Clients resync full state from /api/status
// on (re)connect; the stream carries diffs.
func (s *Server) sse(w http.ResponseWriter, r *http.Request) {
	fl, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "streaming unsupported", 500)
		return
	}
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	ch, cancel := s.bus.Subscribe()
	defer cancel()
	keep := time.NewTicker(20 * time.Second)
	defer keep.Stop()

	fmt.Fprint(w, ": connected\n\n")
	fl.Flush()
	for {
		select {
		case <-r.Context().Done():
			return
		case <-keep.C:
			fmt.Fprint(w, ": keepalive\n\n")
			fl.Flush()
		case ev, ok := <-ch:
			if !ok {
				return
			}
			fmt.Fprintf(w, "event: %s\ndata: %s\n\n", ev.Kind, ev.JSON())
			fl.Flush()
		}
	}
}

// static serves the embedded SPA with index.html fallback for client routes.
func (s *Server) static(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/")
	if path == "" {
		path = "index.html"
	}
	if _, err := fs.Stat(s.ui, path); err != nil {
		path = "index.html" // SPA fallback
	}
	http.ServeFileFS(w, r, s.ui, path)
}

// ListenAndServe runs the HTTPS API (and, when plainAddr is non-empty,
// a plaintext sidecar serving only /healthz + /metrics and redirecting
// the rest) until ctx is cancelled. The plaintext listener is optional
// by requirement — HTTPS-only sites pass -listen "".
func (s *Server) ListenAndServe(ctx context.Context, tlsAddr, certFile, keyFile, plainAddr string) error {
	srv := &http.Server{Addr: tlsAddr, Handler: s.Handler()}
	errCh := make(chan error, 2)
	go func() { errCh <- srv.ListenAndServeTLS(certFile, keyFile) }()
	s.log.Info("API listening (TLS)", "addr", tlsAddr)

	var plain *http.Server
	if plainAddr != "" {
		plain = &http.Server{Addr: plainAddr, Handler: s.plainHandler(tlsAddr)}
		go func() { errCh <- plain.ListenAndServe() }()
		s.log.Info("plaintext listener (metrics/health + redirect)", "addr", plainAddr)
	}

	shutdown := func() {
		sctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		srv.Shutdown(sctx)
		if plain != nil {
			plain.Shutdown(sctx)
		}
	}
	select {
	case <-ctx.Done():
		shutdown()
		return nil
	case err := <-errCh:
		shutdown()
		return err
	}
}

// plainHandler is the whole surface of the optional HTTP listener:
// scrape + health stay plaintext for tooling, everything else is sent
// to the TLS port.
func (s *Server) plainHandler(tlsAddr string) http.Handler {
	_, tlsPort, err := net.SplitHostPort(tlsAddr)
	if err != nil {
		tlsPort = "8443"
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/healthz":
			s.healthz(w, r)
		case "/metrics":
			s.metrics(w, r)
		default:
			host := r.Host
			if h, _, err := net.SplitHostPort(host); err == nil {
				host = h
			}
			http.Redirect(w, r, "https://"+net.JoinHostPort(host, tlsPort)+r.URL.RequestURI(), http.StatusPermanentRedirect)
		}
	})
}
