#!/usr/bin/env bash
#
# OpenVTL — stage mhVTL kernel-module sources into the DKMS source tree
# (/usr/src/mhvtl-<ver>), paired with OpenVTL's dkms.conf.
#
# We copy the upstream kernel/ tree (sources, headers, AND upstream's
# Makefile — DKMS builds with it) and layer only our dkms.conf on top. The
# upstream userspace (vtltape/vtllibrary/tools) is built separately, not
# via DKMS.
#
# mhVTL is GPLv2 — sources come from the vendored tarball in third_party/,
# unpacked (and patched) by packaging/install.sh; nothing is fetched from
# the network at build time.
#
# Usage:
#   sudo ./stage-sources.sh --src /path/to/mhvtl --version 1.7.4
#
#   --src       Path to an unpacked mhVTL source tree (upstream: https://github.com/markh794/mhvtl)
#   --version   Version string for the DKMS package (becomes mhvtl-<version>)
#
set -euo pipefail

log()  { printf '\033[1;32m[+]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SRC=""
VERSION=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --src)     SRC="${2:?}"; shift 2 ;;
    --version) VERSION="${2:?}"; shift 2 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)         die "Unknown argument: $1" ;;
  esac
done

[[ $EUID -eq 0 ]]    || die "Run as root (writes under /usr/src)."
[[ -n "$SRC" ]]      || die "--src is required."
[[ -n "$VERSION" ]]  || die "--version is required."
[[ -d "$SRC/kernel" ]] || die "No kernel/ directory under '$SRC' — is this an mhVTL checkout?"
[[ -f "$SCRIPT_DIR/dkms.conf.in" ]]  || die "Missing template: $SCRIPT_DIR/dkms.conf.in"

DEST="/usr/src/mhvtl-${VERSION}"

# The mhVTL module is NOT a single source file: mhvtl.c is built together with
# version-specific fetch*.c sources and EL/RHEL backport handling that ONLY
# upstream's kernel/Makefile wires up correctly (object selection + CFLAGS per
# kernel). We therefore stage upstream's Makefile and let it drive the build;
# DKMS still controls which kernel it builds against, so auto-rebuild is intact.
if [[ ! -f "$SRC/kernel/Makefile" && ! -f "$SRC/kernel/Kbuild" ]]; then
  die "No Makefile/Kbuild in $SRC/kernel — cannot build the mhVTL module."
fi

log "Staging mhVTL ${VERSION} sources into ${DEST}"
rm -rf "$DEST"
mkdir -p "$DEST"

# Copy the ENTIRE kernel/ tree (all sources, headers, AND upstream's Makefile).
find "$SRC/kernel" -maxdepth 1 -type f -exec cp -v {} "$DEST/" \;

# mhvtl.c uses quote-includes (e.g. "vtl_common.h") that live in the repo's
# include/ and include/common/ dirs. Under the DKMS build layout the Makefile's
# relative -I../include/common does not resolve, so stage those headers FLAT
# alongside the sources — quote-includes then resolve in the source directory.
for d in include include/common; do
  if compgen -G "$SRC/$d/"'*.h' >/dev/null; then
    cp -v "$SRC/$d/"*.h "$DEST/"
  fi
done

# mhVTL's config.h is generated by config.sh and is KERNEL-DEPENDENT (config.sh
# requires KDIR). It must be regenerated for the kernel being built, so we do NOT
# generate it at stage time — instead we install a PRE_BUILD wrapper that DKMS
# runs against the target kernel ($1 = kernel version) before each compile. This
# keeps autoinstall correct across kernel updates (the G1 milestone).
if [[ -f "$DEST/config.sh" ]]; then
  cat > "$DEST/dkms-prebuild.sh" <<'PREBUILD'
#!/bin/sh
# Regenerate mhVTL config.h for the kernel DKMS is building.
# DKMS exports $kernelver to build scripts; fall back to the running kernel.
KVER="${kernelver:-$(uname -r)}"
KDIR="/lib/modules/${KVER}/build"
export KDIR
# Run under bash explicitly: upstream config.sh is #!/usr/bin/env bash and uses
# bashisms (declare -A, [[ ]]). On Debian /bin/sh is dash, which fails the array
# assignment with a syntax error (exit 2); on RHEL/Rocky /bin/sh is bash so `sh`
# happened to work. Force bash so config.h regenerates on every DKMS (re)build.
exec bash ./config.sh
PREBUILD
  chmod +x "$DEST/dkms-prebuild.sh"
  log "Installed PRE_BUILD hook: ${DEST}/dkms-prebuild.sh"
else
  warn "No config.sh in upstream kernel/ — PRE_BUILD hook not installed; verify the build."
fi

# Layer only our DKMS metadata on top — do not touch upstream's Makefile.
sed "s/@PKGVER@/${VERSION}/g" "$SCRIPT_DIR/dkms.conf.in" > "$DEST/dkms.conf"
log "Wrote ${DEST}/dkms.conf"

cat <<EOF

$(log "Staging complete: ${DEST}")

  Contents:
$(ls -1 "$DEST" | sed 's/^/    /')

  Next: register and build with DKMS:
        sudo packaging/dkms/install-dkms.sh --version ${VERSION}
EOF
